#!/usr/bin/env bun
import { readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const MONTHS = [
  'january', 'february', 'march', 'april', 'may', 'june',
  'july', 'august', 'september', 'october', 'november', 'december',
];

const PHOTOS_ROOT = join(process.cwd(), 'public/photos');
const OUT_FILE = join(process.cwd(), 'data/galleries.generated.ts');

const photosByMonth: Record<string, string[]> = {};
for (const month of MONTHS) {
  const dir = join(PHOTOS_ROOT, month);
  if (!existsSync(dir)) {
    photosByMonth[month] = [];
    continue;
  }
  // Non-recursive: files in archived/ subfolders are excluded automatically
  photosByMonth[month] = readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /\.(jpe?g)$/i.test(entry.name))
    .map((entry) => entry.name)
    .sort();
}

const contents = `// Auto-generated by scripts/generate-galleries.ts — do not edit by hand.
// Regenerate with \`bun run photos:scan\`.
export const PHOTOS_BY_MONTH: Record<string, readonly string[]> = ${JSON.stringify(photosByMonth, null, 2)} as const;
`;

writeFileSync(OUT_FILE, contents);

const total = Object.values(photosByMonth).reduce((sum, files) => sum + files.length, 0);
console.log(`Wrote ${OUT_FILE} (${total} photos across ${MONTHS.length} months)`);
for (const [month, files] of Object.entries(photosByMonth)) {
  if (files.length > 0) console.log(`  ${month}: ${files.length}`);
}
