#!/usr/bin/env bun
import { readdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';

const MONTHS = [
  'january', 'february', 'march', 'april', 'may', 'june',
  'july', 'august', 'september', 'october', 'november', 'december',
];

const PHOTOS_ROOT = join(process.cwd(), 'public/photos');
const OUT_FILE = join(process.cwd(), 'data/galleries.generated.ts');

type PhotoEntry = { file: string; blurDataURL: string };

async function makeBlurDataURL(path: string): Promise<string> {
  const input = readFileSync(path);
  const buf = await sharp(input)
    .resize({ width: 12, fit: 'inside' })
    .jpeg({ quality: 40 })
    .toBuffer();
  return `data:image/jpeg;base64,${buf.toString('base64')}`;
}

const photosByMonth: Record<string, PhotoEntry[]> = {};
for (const month of MONTHS) {
  const dir = join(PHOTOS_ROOT, month);
  if (!existsSync(dir)) {
    photosByMonth[month] = [];
    continue;
  }
  const files = readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /\.(jpe?g)$/i.test(entry.name))
    .map((entry) => entry.name)
    .sort();
  const entries: PhotoEntry[] = [];
  for (const file of files) {
    const blurDataURL = await makeBlurDataURL(join(dir, file));
    entries.push({ file, blurDataURL });
  }
  photosByMonth[month] = entries;
}

const contents = `// Auto-generated by scripts/generate-galleries.ts — do not edit by hand.
// Regenerate with \`bun run photos:scan\`.
export type PhotoEntry = { file: string; blurDataURL: string };
export const PHOTOS_BY_MONTH: Record<string, readonly PhotoEntry[]> = ${JSON.stringify(photosByMonth, null, 2)} as const;
`;

writeFileSync(OUT_FILE, contents);

const total = Object.values(photosByMonth).reduce((sum, files) => sum + files.length, 0);
console.log(`Wrote ${OUT_FILE} (${total} photos across ${MONTHS.length} months)`);
for (const [month, files] of Object.entries(photosByMonth)) {
  if (files.length > 0) console.log(`  ${month}: ${files.length}`);
}
